name: CONVERTinator CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
    - name: Copy Code
      uses: actions/checkout@v4
      
    - name: Install .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore Packages
      run: dotnet restore
      
    - name: Build Project
      run: dotnet build --no-restore --configuration Release
      
    - name: Run Tests (BRONYA)
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Prepare Files for Publication (Publish)
      run: dotnet publish CONVERTinator.WebAPI/CONVERTinator.WebAPI.csproj -c Release -o ./myapp
      
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'convertinator-app-2026' 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./myapp