name: CONVERTinator CI (Tests & Build)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Copy Code
      uses: actions/checkout@v4
      
    - name: Install .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore Packages
      run: dotnet restore
      
    - name: Build Project
      run: dotnet build --no-restore --configuration Release
      
    - name: Run Tests (BRONYA)
      run: dotnet test --no-build --verbosity normal --configuration Release